https://developers.liveperson.com:
  type: upstream
  upstream: jekyll_app:http
  tls:
    min_version: TLSv1.2
  cache:
    enabled: true
    default_ttl: 0
    cookies: ['*']
    headers: ['Accept', 'Accept-Language']
  redirects:
    expires: 1d
    paths:
      '^/test/images/(.*)':
        to: 'https://{default}/img/$1'
        regexp: true